FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

RUN apt-get update && apt-get install

RUN apt-get install -y \
  dos2unix \
  libpq-dev \
  libmariadb-dev-compat \
  libmariadb-dev \
  gcc \
  python3-psycopg2 \
  && apt-get clean

COPY ./app/api/requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY ./app/api /app